version: '3'
services:
  restapi:
      build: ./python
      container_name: nextjs_restapi
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
        - ./static:/static
      expose:
        - "8001"
      ports:
        - 8000:8000
        # デバッグ用にポートを追加
        - 8888:8888
