# Generated by Django 3.1 on 2021-01-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aaa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AAA',
        ),
    ]
